name: scrape-to-shape
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10,<3.12
  - pip>=23.0
  # Data Processing
  - pandas>=2.0
  - numpy>=1.24
  - openpyxl>=3.0
  # Data Visualization
  - matplotlib>=3.7
  - seaborn>=0.12
  # Machine Learning
  - scikit-learn>=1.3
  # Development
  - jupyter
  - ipykernel
  # Pip dependencies (not available or better via pip)
  - pip:
    - playwright>=1.40.0
    - beautifulsoup4>=4.12.0
    - lxml>=4.9.0
    - spacy>=3.7.0
    - wordcloud>=1.9.0

